fail_fast: true
repos:
# Format code to pattern (Black)
-   repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    -   id: black
        language_version: python3
        exclude: ^ui/generated/
# Checking if large files are present
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-added-large-files
# Checking code compliance to pep8 (Flake 8, McCabe)
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        exclude: ^ui/generated/
# Sorting imports (isort)
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
        exclude: ^ui/generated/
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.1
    hooks:
    -   id: isort
        exclude: ^ui/generated/
